services:
- type: web
  name: crud-escolar
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app_laravel:app
  envVars:
  - key: DATABASE_URL
    sync: false